// <auto-generated />
using CarFleet_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarFleet_Project.Migrations
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20230821112812_First-Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarFleet_Project.Models.Vehicle", b =>
                {
                    b.Property<int>("vehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vehicleId"));

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("carBodyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("doorsAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("fuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("mileage")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("yearOfProduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("vehicleId");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
